// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "DriveTurn.h"
DriveTurn::DriveTurn(float power,float time=1.0) {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::driveTrain);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	m_power=power;
	m_time=time;
}
// Called just before this Command runs the first time
void DriveTurn::Initialize() {
	SetTimeout(m_time);
}
// Called repeatedly when this Command is scheduled to run
void DriveTurn::Execute() {
	Robot::driveTrain->tankDrive(-m_power,m_power);
	
}
// Make this return true when this Command no longer needs to run execute()
bool DriveTurn::IsFinished() {
	return IsTimedOut();
}
// Called once after isFinished returns true
void DriveTurn::End() {
	Robot::driveTrain->tankDrive(0,0);
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void DriveTurn::Interrupted() {
	End();
}
