// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "DriveTrain.h"
#include "../Robotmap.h"
#include "../Commands/DriveWithJoystick.h"
DriveTrain::DriveTrain() : Subsystem("DriveTrain") {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	driveLeft1 = RobotMap::driveTrainDriveLeft1;
	driveRight1 = RobotMap::driveTrainDriveRight1;
	robotDrive = RobotMap::driveTrainRobotDrive;
	ultrasonicDistance = RobotMap::driveTrainultrasonicDistance;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}
    
void DriveTrain::InitDefaultCommand() {
	// Set the default command for a subsystem here.
	//SetDefaultCommand(new MySpecialCommand());
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	SetDefaultCommand(new DriveWithJoystick());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
}
void DriveTrain::tankDrive(float leftstick, float rightstick) {
	robotDrive->TankDrive(leftstick, rightstick);
}
// Put methods for controlling this subsystem
// here. Call these from Commands.
float DriveTrain::getDistance()
{
	dVoltage = ultrasonicDistance->GetVoltage();
	// distance is in inches
	distance = dVoltage / 0.0098; 
	
	return distance;
}
