// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "Feeder.h"
#include "../Robotmap.h"
#define FEEDER_MOTOR_VOLTAGE 0.5 
Feeder::Feeder() : Subsystem("Feeder") {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	feederMotor = RobotMap::feederFeederMotor;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}
    
void Feeder::InitDefaultCommand() {
	// Set the default command for a subsystem here.
	//SetDefaultCommand(new MySpecialCommand());
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}
// Put methods for controlling this subsystem
// here. Call these from Commands.
void Feeder::Feed()
{
	feederMotor->Set(-FEEDER_MOTOR_VOLTAGE); //This voltage was originally set to 2.0, determined that the
											 //value of 0.5 worked, and then defined it at the top of the 
											 //file.					
}
void Feeder::Reset()
{
	feederMotor->Set(FEEDER_MOTOR_VOLTAGE);
}
void Feeder::turnOff()
{
	feederMotor->Set(0.0);
}
